version: '3.4'

services:
  workflow-loader:
    build: .
    image: webpals/workflow-loader
    container_name: workflow-loader
    network_mode: host
    volumes:
      - ./src/test/resources/repository:/usr/apps/workflow-loader/repository
    environment:
      - ZEEBE_HOST=127.0.0.1
      - ZEEBE_PORT=26500
      - REPOSITORY=repository
      - SERVICE=service1
      - WF_NAME="test1.bpmn"