= microservice-orchestration-poc
Playing with microservice orchestration

== Netflix Conductor
=== conductor-tools
Helper classes.

=== nodejs-worker1
Example of worker on Node JS.

=== simple-workers
Example codes:
 - worker
 - programmatic task and workflow definitions
 - running workflow

See link:netflix-conductor/simple-workers/README.adoc[simple-workers]

== Zeebe
=== zeebe-app1
See link:zeebe/zeebe-app1/README.adoc[zeebe-app1]

=== zeebe-app2
See link:zeebe/zeebe-app2/README.adoc[zeebe-app2]

=== zeebe-condition1
See link:zeebe/zeebe-condition1/README.adoc[zeebe-condition1]

=== zeebe-dmn1
See link:zeebe/zeebe-dmn1/README.adoc[zeebe-dmn1]

=== zeebe-err1
See link:zeebe/zeebe-err1/README.adoc[zeebe-err1]

=== zeebe-management
See link:zeebe/zeebe-management/README.adoc[zeebe-management]

=== zeebe-msg1
See link:zeebe/zeebe-msg1/README.adoc[zeebe-msg1]

=== zeebe-nodejs1
See link:zeebe/zeebe-nodejs1/README.adoc[zeebe-nodejs1]

=== zeebe-start
See link:zeebe/zeebe-start/README.adoc[zeebe-start]

=== zeebe-test1
See link:zeebe/zeebe-start/README.adoc[zeebe-test1]


